import { spawn } from 'child_process';
import fs from 'fs';
import path from 'path';
import os from 'os';

export interface StrixScanParams {
  runId: string;
  targets: string[];
  targetType: string; // 'url' | 'repo' | 'dir' | 'whitebox' | 'list'
  mode: 'quick' | 'standard' | 'deep';
  llm: string; // requested primary model (LiteLLM format)
  instructions?: string;
  runDir: string; // strix_runs/<runId> — used as the isolated cwd for this scan
}

// Backup models, in LiteLLM format (https://github.com/usestrix/strix).
// The model requested for the scan is tried first; if its provider fails,
// Strix is re-run against each of these in turn. Override with STRIX_LLM_FALLBACKS
// (a comma-separated list), e.g. "openai/gpt-5.4,openrouter/z-ai/glm-5.3".
const DEFAULT_FALLBACK_MODELS = [
  'anthropic/claude-sonnet-4-6',
  'openai/gpt-5.4',
  'openrouter/z-ai/glm-5.3',
];

// Exit codes Strix uses for a successful run: 0 (no findings) or 2 (findings
// were reported). Anything else is a genuine failure worth a model fallback.
const STRIX_SUCCESS_CODES = new Set([0, 2]);

function resolveModelChain(primary: string): string[] {
  const configured = process.env.STRIX_LLM_FALLBACKS;
  const fallbacks = configured
    ? configured.split(',').map(s => s.trim()).filter(Boolean)
    : DEFAULT_FALLBACK_MODELS;
  return [...new Set([primary, ...fallbacks].filter(Boolean))];
}

function resolveStrixBin(): string | null {
  const explicit = process.env.STRIX_BIN;
  if (explicit && fs.existsSync(/*turbopackIgnore: true*/ explicit)) return explicit;
  const home = path.join(os.homedir(), '.strix', 'bin', 'strix');
  if (fs.existsSync(/*turbopackIgnore: true*/ home)) return home;
  return null; // fall back to a PATH lookup of `strix`
}

function buildArgs(params: StrixScanParams): string[] {
  const { targets, targetType, mode, instructions } = params;
  const args: string[] = [];
  if (targetType === 'list') {
    args.push('--target-list', targets[0]);
  } else {
    targets.forEach(t => args.push('--target', t));
  }
  // `-n` runs headless (no TUI); `--scan-mode` sets depth.
  args.push('--scan-mode', mode, '-n');
  if (instructions) args.push('--instruction', instructions);
  return args;
}

// Run Strix once against a single model. Resolves with the process exit code,
// or -1 when the binary could not be launched at all (e.g. not installed).
function runStrixOnce(
  command: string,
  args: string[],
  model: string,
  cwd: string,
  logPath: string,
): Promise<number> {
  return new Promise(resolve => {
    const env = {
      ...process.env,
      STRIX_LLM: model,
      LLM_API_KEY:
        process.env.LLM_API_KEY ||
        process.env.ANTHROPIC_API_KEY ||
        process.env.OPENAI_API_KEY ||
        '',
      PATH: `${path.join(os.homedir(), '.strix', 'bin')}:${process.env.PATH || ''}`,
    };

    let child;
    try {
      child = spawn(/*turbopackIgnore: true*/ command, args, { cwd, env });
    } catch {
      resolve(-1);
      return;
    }

    const out = fs.createWriteStream(logPath, { flags: 'a' });
    child.stdout?.pipe(out);
    child.stderr?.pipe(out);

    child.on('error', () => {
      out.end();
      resolve(-1);
    });
    child.on('close', code => {
      out.end();
      resolve(code ?? -1);
    });
  });
}

// Runs a real Strix penetration test. Strix writes its results (findings.sarif,
// logs, reports) into <runDir>/strix_runs/<auto-generated-name>/, which the
// status route resolves when polling. This never fabricates findings: if Strix
// is unavailable or every model fails, the run is marked as errored.
export async function runStrixScan(params: StrixScanParams): Promise<void> {
  const { runId, targets, mode, runDir } = params;
  const metaPath = path.join(path.dirname(runDir), `${runId}.meta.json`);
  const logPath = path.join(runDir, 'strix.log');

  fs.mkdirSync(runDir, { recursive: true });

  const appendLog = (line: string) => {
    const ts = new Date().toISOString().replace('T', ' ').substring(0, 19);
    try {
      fs.appendFileSync(logPath, `[${ts}] ${line}\n`);
    } catch {
      /* best-effort logging */
    }
  };

  const patchMeta = (patch: Record<string, unknown>) => {
    try {
      const meta = fs.existsSync(metaPath)
        ? JSON.parse(fs.readFileSync(metaPath, 'utf8'))
        : {};
      fs.writeFileSync(metaPath, JSON.stringify({ ...meta, ...patch }, null, 2));
    } catch {
      /* best-effort metadata */
    }
  };

  const bin = resolveStrixBin();
  const command = bin || 'strix';
  const models = resolveModelChain(params.llm);
  const args = buildArgs(params);

  appendLog(`[orchestrator] Starting Strix penetration test for: ${targets.join(', ')}`);
  appendLog(`[orchestrator] Scan mode: ${mode} | Model priority: ${models.join(' -> ')}`);

  for (let i = 0; i < models.length; i++) {
    const model = models[i];
    appendLog(`[orchestrator] Launching Strix with model "${model}"`);
    patchMeta({ status: 'running', activeModel: model });

    const code = await runStrixOnce(command, args, model, runDir, logPath);

    if (STRIX_SUCCESS_CODES.has(code)) {
      appendLog(`[orchestrator] Strix completed with "${model}" (exit ${code}).`);
      patchMeta({
        status: 'complete',
        activeModel: model,
        completedAt: new Date().toISOString(),
      });
      return;
    }

    if (code === -1 && !bin) {
      // The binary could not be launched and no install was found — no point
      // retrying other models, the failure is environmental.
      break;
    }

    const more = i < models.length - 1;
    appendLog(
      `[orchestrator] Model "${model}" failed (exit ${code}).` +
        (more ? ' Falling back to the next model…' : ' No more fallback models.'),
    );
  }

  if (!bin) {
    appendLog(
      '[error] Strix was not found. Install it (https://github.com/usestrix/strix) ' +
        'and set STRIX_BIN, or add `strix` to PATH. No scan was run.',
    );
    patchMeta({ status: 'error', error: 'Strix is not installed or not on PATH.' });
    return;
  }

  appendLog(
    '[error] Every configured model failed. Check LLM_API_KEY / provider quota, ' +
      'that Docker is running, and the target scope.',
  );
  patchMeta({ status: 'error', error: 'Strix scan failed for every configured model.' });
}
